title: Techn0tz
description: Where learning turns into something you can build.
remote_theme: pages-themes/dinky
url: "https://manjushaps.github.io"
baseurl: ""
author: manjushaps
permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  
